export const estados = {
    aguascalientes: "Aguascalientes",
    bajacalifornia: "Baja California",
    bajasur: "Baja California Sur",
    campeche: "Campeche",
    chiapas: "Chiapas",
    chihuahua: "Chihuahua",
    coahuila: "Coahuila de Zaragoza",
    colima: "Colima",
    cdmx: "CDMX",
    durango: "Durango",
    edomex: "Estado de México",
    guanajuato: "Guanajuato",
    guerrero: "Guerrero",
    hidalgo: "Hidalgo",
    jalisco: "Jalisco",
    michoacan: "Michoacán",
    morelos: "Morelos",
    nayarit: "Nayarit",
    nuevoleon: "Nuevo León",
    oaxaca: "Oaxaca",
    puebla: "Puebla",
    queretaro: "Querétaro",
    quintanaroo: "Quintana Roo",
    sanluis: "San Luis Potosí",
    sinaloa: "Sinaloa",
    sonora: "Sonora",
    tabasco: "Tabasco",
    tamaulipas: "Tamaulipas",
    tlaxcala: "Tlaxcala",
    veracruz: "Veracruz",
    yucatan: "Yucatán",
    zacatecas: "Zacatecas",
  };